development:
  adapter: mysql2
  encoding: utf8
  database: jogging_api
  username: root
  password: root
  variables:
    sql_mode: TRADITIONAL

test:
  adapter: mysql2
  encoding: utf8
  database: jogging_api_test
  username: root
  password: root
  variables:
    sql_mode: TRADITIONAL
